name: sealed_annotations
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_annotations
homepage: https://github.com/6thsolution/dart_sealed

version: 1.9.0

# remove this when publishing
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: any
  equatable: ^2.0.0

dev_dependencies:
  pedantic: any
  test: any
