targets:
  $default:
    builders:
      super_enum_sealed_generators:
        enabled: true

builders:
  super_enum_sealed_generators:
    target: ":super_enum_sealed_generators"
    import: "package:super_enum_sealed_generators/super_enum_sealed_generators.dart"
    builder_factories: [ "sealedSuperEnumMapperBuilder" ]
    build_extensions: { ".dart": [ ".super.dart" ] }
    auto_apply: dependents
    build_to: source
