name: example
description: dart sealed example.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sealed_annotations:
    path: ../sealed_annotations

dev_dependencies:
  pedantic: ^1.9.0
  sealed_generators:
    path: ../sealed_generators
