name: sealed_example
description: Dart and Flutter sealed class generator and annotations.
version: 0.1.0
homepage: https://github.com/6thsolution/dart_sealed
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sealed_annotations:
    path: ../sealed_annotations

dev_dependencies:
  sealed_generators:
    path: ../sealed_generators
  pedantic: ^1.11.0
  test: ^1.17.0
  build_runner: ^2.0.0
