name: sealed_example
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_example
homepage: https://github.com/6thsolution/dart_sealed

version: 1.8.0

# example package should not be published
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sealed_annotations: '>=1.7.0 <1.8.0'

dev_dependencies:
  sealed_generators: '>=1.7.0 <1.8.0'
  pedantic: ^1.11.0
  test: ^1.17.10
  build_runner: ^2.1.1
