name: super_enum_sealed_example
description: Dart and Flutter sealed class generator and annotations based on super_enum API.
version: 1.0.0
homepage: https://github.com/6thsolution/dart_sealed

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  super_enum_sealed_annotations:
    path: ../super_enum_sealed_annotations

dev_dependencies:
  super_enum_sealed_generators:
    path: ../super_enum_sealed_generators
  pedantic: ^1.11.0
  test: ^1.17.0
  build_runner: ^2.0.0
