name: super_enum_sealed_example
description: Dart and Flutter sealed class generator and annotations based on super_enum API.
repository: https://github.com/6thsolution/dart_sealed/tree/master/super_enum_sealed_example
homepage: https://github.com/6thsolution/dart_sealed

version: 1.0.0

# example package should not be published
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  super_enum_sealed_annotations: '>=1.0.0 <1.1.0'

dev_dependencies:
  super_enum_sealed_generators: '>=1.0.0 <1.1.0'
  pedantic: ^1.11.0
  test: ^1.17.0
  build_runner: ^2.0.0
