name: sealed_writer
description: Dart and Flutter sealed class generator and annotations.
version: 0.1.0
homepage: https://github.com/6thsolution/dart_sealed

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
