name: super_enum_sealed_annotations
description: Dart and Flutter sealed class generator and annotations based on super_enum API.
repository: https://github.com/6thsolution/dart_sealed/tree/master/super_enum_sealed_annotations
homepage: https://github.com/6thsolution/dart_sealed

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  equatable: ^2.0.0
  sealed_annotations: '>=1.0.0 <1.1.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
