name: sealed_generators
description: Dart and Flutter sealed class generator and annotations.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_generators
homepage: https://github.com/6thsolution/dart_sealed

version: 1.0.0

# remove this when publishing
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sealed_annotations:
    path: ../sealed_annotations
  sealed_writer:
    path: ../sealed_writer
  meta: ^1.3.0
  build: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  build_test: ^2.0.0
