name: sealed_generators
description: Dart and Flutter sealed class generator.
version: 0.1.0
homepage: https://github.com/6thsolution/dart_sealed

# todo remove this
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # todo change this
  sealed_annotations:
    path: ../sealed_annotations
  # todo change this
  sealed_writer:
    path: ../sealed_writer
  meta: ^1.3.0
  build: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
  build_test: ^2.1.0
