name: sealed_generators
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_generators
homepage: https://github.com/6thsolution/dart_sealed

version: 1.8.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sealed_annotations:
    path: ../sealed_annotations
  sealed_writer:
    path: ../sealed_writer
  build: any
  source_gen: any
  analyzer: any
  pub_semver: any

dev_dependencies:
  pedantic: any
  test: any
  build_test: any
