name: sealed_generators
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_generators
homepage: https://github.com/6thsolution/dart_sealed

version: 1.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # use fixed version dependency
  sealed_annotations: '1.11.0'
  # use fixed version dependency
  sealed_writer: '1.11.0'
  build: any
  source_gen: any
  analyzer: any
  pub_semver: any

dev_dependencies:
  pedantic: any
  test: any
  build_test: any

# remove this on pub branch
publish_to: 'none'

# remove this on pub branch
dependency_overrides:
  sealed_annotations:
    path: ../sealed_annotations
  sealed_writer:
    path: ../sealed_writer
