targets:
  $default:
    builders:
      sealed_super_enum_mapper:
        enabled: true

builders:
  sealed_super_enum_mapper:
    target: ":sealed_super_enum_mapper"
    import: "package:sealed_super_enum_mapper/sealed_super_enum_mapper.dart"
    builder_factories: [ "sealedSuperEnumMapperBuilder" ]
    build_extensions: { ".dart": [ ".super.dart" ] }
    auto_apply: dependents
    build_to: source
