name: sealed_super_enum_mapper
description: map super_enum manifest to dart_sealed manifest.
version: 0.1.0
homepage: https://github.com/6thsolution/dart_sealed

# todo remove this
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  super_enum: ^0.5.0
  # todo change this
  sealed_annotations:
    path: ../sealed_annotations
  # todo change this
  sealed_generators:
    path: ../sealed_generators
  meta: ^1.3.0
  build: ^2.0.0
  source_gen: ^1.0.0

dependency_overrides:
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_test: ^2.0.0
  build_runner: ^1.12.2
