#!/bin/bash

echo HEADER analyze

pushd sealed_annotations || exit 1
echo NOTE sealed_annotations
dart analyze || exit 1
popd || exit 1

pushd sealed_writer || exit 1
echo NOTE sealed_writer
dart analyze || exit 1
popd || exit 1

pushd sealed_generators || exit 1
echo NOTE sealed_generators
dart analyze || exit 1
popd || exit 1

pushd sealed_example || exit 1
echo NOTE sealed_example
dart analyze || exit 1
popd || exit 1
