#!/bin/bash

echo HEADER analyze

pushd sealed_annotations || exit
echo NOTE sealed_annotations
dart analyze
popd || exit

pushd sealed_writer || exit
echo NOTE sealed_writer
dart analyze
popd || exit

pushd sealed_generators || exit
echo NOTE sealed_generators
dart analyze
popd || exit

pushd sealed_example || exit
echo NOTE sealed_example
dart analyze
popd || exit

pushd super_enum_sealed_annotations || exit
echo NOTE super_enum_sealed_annotations
dart analyze
popd || exit

pushd super_enum_sealed_generators || exit
echo NOTE super_enum_sealed_generators
dart analyze
popd || exit

pushd super_enum_sealed_example || exit
echo NOTE super_enum_sealed_example
dart analyze
popd || exit
