#!/bin/bash

echo COPY EXAMPLE FILES

cp example/bin/sealed/nullsafe/data/simple/weather.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/weather.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/mixed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/mixed.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/meta.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/meta.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/common.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/common.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result_complex.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result_complex.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/hierarchy.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/simple/hierarchy.sealed.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result_hierarchy.dart sealed_annotations/example/
cp example/bin/sealed/nullsafe/data/generic/result_hierarchy.sealed.dart sealed_annotations/example/

cp example/bin/sealed/nullsafe/data/simple/weather.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/weather.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/mixed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/mixed.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/meta.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/meta.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/common.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/common.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result_complex.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result_complex.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/hierarchy.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/simple/hierarchy.sealed.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result_hierarchy.dart sealed_generators/example/
cp example/bin/sealed/nullsafe/data/generic/result_hierarchy.sealed.dart sealed_generators/example/

echo DONE
