#!/bin/bash

echo HEADER format

pushd sealed_annotations || exit 1
echo NOTE sealed_annotations
dart format --fix lib test
popd || exit 1

pushd sealed_writer || exit 1
echo NOTE sealed_writer
dart format --fix lib test
popd || exit 1

pushd sealed_generators || exit 1
echo NOTE sealed_generators
dart format --fix lib test
popd || exit 1

pushd sealed_example || exit 1
echo NOTE sealed_example
dart format --fix test
popd || exit 1
