#!/bin/bash

echo HEADER format

pushd sealed_annotations || exit 1
echo NOTE sealed_annotations
dart format --output=none --set-exit-if-changed lib test || exit 1
popd || exit 1

pushd sealed_writer || exit 1
echo NOTE sealed_writer
dart format --output=none --set-exit-if-changed lib test || exit 1
popd || exit 1

pushd sealed_generators || exit 1
echo NOTE sealed_generators
dart format --output=none --set-exit-if-changed lib test || exit 1
popd || exit 1

pushd sealed_example || exit 1
echo NOTE sealed_example
dart format --output=none --set-exit-if-changed test || exit 1
popd || exit 1

pushd super_enum_sealed_annotations || exit 1
echo NOTE super_enum_sealed_annotations
dart format --output=none --set-exit-if-changed lib test || exit 1
popd || exit 1

pushd super_enum_sealed_generators || exit 1
echo NOTE super_enum_sealed_generators
dart format --output=none --set-exit-if-changed lib test || exit 1
popd || exit 1

pushd super_enum_sealed_example || exit 1
echo NOTE super_enum_sealed_example
dart format --output=none --set-exit-if-changed test || exit 1
popd || exit 1
