#!/bin/bash

pushd sealed_annotations || exit
echo init sealed_annotations
dart pub get
popd || exit
pushd sealed_generators || exit
echo init sealed_generators
dart pub get
popd || exit
pushd example || exit
echo init example
dart pub get
popd || exit
pushd sealed_super_enum_mapper || exit
echo init sealed_super_enum_mapper
dart pub get
popd || exit
pushd sealed_super_enum_mapper_example || exit
echo init sealed_super_enum_mapper_example
dart pub get
popd || exit
