#!/bin/bash

echo HEADER test

pushd sealed_annotations || exit 1
echo NOTE sealed_annotations
dart test || exit 1
popd || exit 1

pushd sealed_writer || exit 1
echo NOTE sealed_writer
dart test || exit 1
popd || exit 1

pushd sealed_generators || exit 1
echo NOTE sealed_generators
dart test || exit 1
popd || exit 1

pushd sealed_example || exit 1
echo NOTE sealed_example
dart test || exit 1
popd || exit 1
