#!/bin/bash

echo HEADER test

pushd sealed_annotations || exit
echo NOTE sealed_annotations
dart test
popd || exit

pushd sealed_writer || exit
echo NOTE sealed_writer
dart test
popd || exit

pushd sealed_generators || exit
echo NOTE sealed_generators
dart test
popd || exit

pushd sealed_example || exit
echo NOTE sealed_example
dart test
popd || exit

pushd super_enum_sealed_annotations || exit
echo NOTE super_enum_sealed_annotations
dart test
popd || exit

pushd super_enum_sealed_generators || exit
echo NOTE super_enum_sealed_generators
dart test
popd || exit

pushd super_enum_sealed_example || exit
echo NOTE super_enum_sealed_example
dart test
popd || exit
