#!/bin/bash

echo HEADER init

pushd sealed_annotations || exit 1
echo NOTE sealed_annotations
dart pub upgrade || exit 1
popd || exit 1

pushd sealed_writer || exit 1
echo NOTE sealed_writer
dart pub upgrade || exit 1
popd || exit 1

pushd sealed_generators || exit 1
echo NOTE sealed_generators
dart pub upgrade || exit 1
popd || exit 1

pushd sealed_example || exit 1
echo NOTE sealed_example
dart pub upgrade || exit 1
popd || exit 1
