name: sealed_super_enum_mapper_example
description: map super_enum manifest to dart_sealed manifest examples.
version: 0.1.0
homepage: https://github.com/6thsolution/dart_sealed
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  super_enum: ^0.5.0
  sealed_annotations:
    path: ../sealed_annotations

dependency_overrides:
  equatable: ^2.0.0

dev_dependencies:
  sealed_super_enum_mapper:
    path: ../sealed_super_enum_mapper
  pedantic: ^1.9.0
  test: ^1.16.8
  build_runner: ^1.12.2
