name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: init
        run: .tools/init
      - name: format
        run: .tools/format
      - name: analyze
        run: .tools/analyze
      - name: test sealed_annotations
        working-directory: sealed_annotations
        run: dart test
      - name: test sealed_writer
        working-directory: sealed_writer
        run: dart test
      - name: test sealed_generators
        working-directory: sealed_generators
        run: dart test
      - name: build example
        working-directory: example
        run: dart run build_runner build --delete-conflicting-outputs
      - name: test example
        working-directory: example
        run: dart test
      - name: example
        run: .tools/example
      - name: coverage
        run: .tools/coverage
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
