name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: init
        run: .tools/init
      - name: format
        run: .tools/format
      - name: analyze
        run: .tools/analyze
      - name: build
        run: .tools/build
      - name: test
        run: .tools/test
      - name: coverage
        run: .tools/coverage
      - name: example
        run: .tools/example
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
